// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (user_id, target_url, shortened_url, password, status, expiration_date, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, target_url, shortened_url, password, status, expiration_date, created_at, updated_at, deleted_at
`

type CreateLinkParams struct {
	UserID         pgtype.Int8        `json:"user_id"`
	TargetUrl      string             `json:"target_url"`
	ShortenedUrl   pgtype.Text        `json:"shortened_url"`
	Password       pgtype.Text        `json:"password"`
	Status         string             `json:"status"`
	ExpirationDate pgtype.Timestamptz `json:"expiration_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.TargetUrl,
		arg.ShortenedUrl,
		arg.Password,
		arg.Status,
		arg.ExpirationDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.ShortenedUrl,
		&i.Password,
		&i.Status,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
UPDATE links
SET
    deleted_at = $2
WHERE id = $1
`

type DeleteLinkParams struct {
	ID        int64              `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) error {
	_, err := q.db.Exec(ctx, deleteLink, arg.ID, arg.DeletedAt)
	return err
}

const destroyLink = `-- name: DestroyLink :exec
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DestroyLink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, destroyLink, id)
	return err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT
    id,
    user_id,
    target_url,
    shortened_url,
    status,
    expiration_date,
    created_at,
    updated_at
FROM links
WHERE id = $1 AND delete_at IS NULL
`

type GetLinkByIDRow struct {
	ID             int64              `json:"id"`
	UserID         pgtype.Int8        `json:"user_id"`
	TargetUrl      string             `json:"target_url"`
	ShortenedUrl   pgtype.Text        `json:"shortened_url"`
	Status         string             `json:"status"`
	ExpirationDate pgtype.Timestamptz `json:"expiration_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (GetLinkByIDRow, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i GetLinkByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.ShortenedUrl,
		&i.Status,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByShortenedURL = `-- name: GetLinkByShortenedURL :one
SELECT
    id,
    user_id,
    target_url,
    shortened_url,
    status,
    expiration_date,
    created_at,
    updated_at
FROM links
WHERE shortened_url = $1 AND deleted_at IS NULL
`

type GetLinkByShortenedURLRow struct {
	ID             int64              `json:"id"`
	UserID         pgtype.Int8        `json:"user_id"`
	TargetUrl      string             `json:"target_url"`
	ShortenedUrl   pgtype.Text        `json:"shortened_url"`
	Status         string             `json:"status"`
	ExpirationDate pgtype.Timestamptz `json:"expiration_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLinkByShortenedURL(ctx context.Context, shortenedUrl pgtype.Text) (GetLinkByShortenedURLRow, error) {
	row := q.db.QueryRow(ctx, getLinkByShortenedURL, shortenedUrl)
	var i GetLinkByShortenedURLRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.ShortenedUrl,
		&i.Status,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByTargetURL = `-- name: GetLinkByTargetURL :one
SELECT
    id,
    user_id,
    target_url,
    shortened_url,
    status,
    expiration_date,
    created_at,
    updated_at
FROM links
WHERE target_url = $1 AND deleted_at IS NULL
`

type GetLinkByTargetURLRow struct {
	ID             int64              `json:"id"`
	UserID         pgtype.Int8        `json:"user_id"`
	TargetUrl      string             `json:"target_url"`
	ShortenedUrl   pgtype.Text        `json:"shortened_url"`
	Status         string             `json:"status"`
	ExpirationDate pgtype.Timestamptz `json:"expiration_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLinkByTargetURL(ctx context.Context, targetUrl string) (GetLinkByTargetURLRow, error) {
	row := q.db.QueryRow(ctx, getLinkByTargetURL, targetUrl)
	var i GetLinkByTargetURLRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.ShortenedUrl,
		&i.Status,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT
    id,
    user_id,
    target_url,
    shortened_url,
    status,
    expiration_date,
    created_at,
    updated_at
FROM links
WHERE deleted_at IS NULL
`

type GetLinksRow struct {
	ID             int64              `json:"id"`
	UserID         pgtype.Int8        `json:"user_id"`
	TargetUrl      string             `json:"target_url"`
	ShortenedUrl   pgtype.Text        `json:"shortened_url"`
	Status         string             `json:"status"`
	ExpirationDate pgtype.Timestamptz `json:"expiration_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLinks(ctx context.Context) ([]GetLinksRow, error) {
	rows, err := q.db.Query(ctx, getLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinksRow
	for rows.Next() {
		var i GetLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetUrl,
			&i.ShortenedUrl,
			&i.Status,
			&i.ExpirationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksByStatus = `-- name: GetLinksByStatus :many
SELECT
    id,
    user_id,
    target_url,
    shortened_url,
    status,
    expiration_date,
    created_at,
    updated_at
FROM links
WHERE status = $1 AND deleted_at IS NULL
`

type GetLinksByStatusRow struct {
	ID             int64              `json:"id"`
	UserID         pgtype.Int8        `json:"user_id"`
	TargetUrl      string             `json:"target_url"`
	ShortenedUrl   pgtype.Text        `json:"shortened_url"`
	Status         string             `json:"status"`
	ExpirationDate pgtype.Timestamptz `json:"expiration_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLinksByStatus(ctx context.Context, status string) ([]GetLinksByStatusRow, error) {
	rows, err := q.db.Query(ctx, getLinksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinksByStatusRow
	for rows.Next() {
		var i GetLinksByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetUrl,
			&i.ShortenedUrl,
			&i.Status,
			&i.ExpirationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLink = `-- name: RestoreLink :exec
UPDATE links
SET
    deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreLink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreLink, id)
	return err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET
    target_url = $2,
    status = $3,
    expiration_date = $4,
    updated_at = $5
WHERE id = $1
RETURNING id, user_id, target_url, shortened_url, password, status, expiration_date, created_at, updated_at, deleted_at
`

type UpdateLinkParams struct {
	ID             int64              `json:"id"`
	TargetUrl      string             `json:"target_url"`
	Status         string             `json:"status"`
	ExpirationDate pgtype.Timestamptz `json:"expiration_date"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.TargetUrl,
		arg.Status,
		arg.ExpirationDate,
		arg.UpdatedAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.ShortenedUrl,
		&i.Password,
		&i.Status,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLinkShortenedURL = `-- name: UpdateLinkShortenedURL :one
UPDATE links
SET
    shortened_url = $2
WHERE id = $1
RETURNING id, user_id, target_url, shortened_url, password, status, expiration_date, created_at, updated_at, deleted_at
`

type UpdateLinkShortenedURLParams struct {
	ID           int64       `json:"id"`
	ShortenedUrl pgtype.Text `json:"shortened_url"`
}

func (q *Queries) UpdateLinkShortenedURL(ctx context.Context, arg UpdateLinkShortenedURLParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLinkShortenedURL, arg.ID, arg.ShortenedUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.ShortenedUrl,
		&i.Password,
		&i.Status,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
