// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analytic struct {
	LinkID          pgtype.Int8        `json:"link_id"`
	TotalClicks     int32              `json:"total_clicks"`
	UniqueClicks    int32              `json:"unique_clicks"`
	IsHuman         pgtype.Bool        `json:"is_human"`
	DeviceType      pgtype.Text        `json:"device_type"`
	OperatingSystem pgtype.Text        `json:"operating_system"`
	Browser         pgtype.Text        `json:"browser"`
	Country         pgtype.Text        `json:"country"`
	Referrer        pgtype.Text        `json:"referrer"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Link struct {
	ID             int64              `json:"id"`
	UserID         pgtype.Int8        `json:"user_id"`
	TargetUrl      string             `json:"target_url"`
	ShortenedUrl   pgtype.Text        `json:"shortened_url"`
	Password       pgtype.Text        `json:"password"`
	Status         string             `json:"status"`
	ExpirationDate pgtype.Timestamptz `json:"expiration_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID        int64              `json:"id"`
	UserName  string             `json:"user_name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
